// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildDictionary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BuildDictionary'](arg1, arg2, arg3, arg4);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConvertKoboDictionary(arg1) {
  return window['go']['main']['App']['ConvertKoboDictionary'](arg1);
}

export function DeleteDeviceDictFile(arg1) {
  return window['go']['main']['App']['DeleteDeviceDictFile'](arg1);
}

export function DeleteLocalDictFile(arg1) {
  return window['go']['main']['App']['DeleteLocalDictFile'](arg1);
}

export function GetDeviceDictionaries() {
  return window['go']['main']['App']['GetDeviceDictionaries']();
}

export function GetLocalDictionaries() {
  return window['go']['main']['App']['GetLocalDictionaries']();
}

export function GetWikiDetails(arg1) {
  return window['go']['main']['App']['GetWikiDetails'](arg1);
}

export function ReadLocalDictionary(arg1) {
  return window['go']['main']['App']['ReadLocalDictionary'](arg1);
}

export function SelectDevice() {
  return window['go']['main']['App']['SelectDevice']();
}
