// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dict} from '../models';
import {frontend} from '../models';

export function BuildDictionary(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<dict.Dict>;

export function SelectDirectory(arg1:frontend.OpenDialogOptions):Promise<string>;
