// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function BuildDictionary(arg1:string,arg2:string,arg3:number,arg4:string):Promise<core.Response[github>;

export function CheckForUpdate():Promise<boolean>;

export function ConvertKoboDictionary(arg1:string):Promise<core.Response[string]>;

export function DeleteDeviceDictFile(arg1:string):Promise<core.Response[string]>;

export function DeleteLocalDictFile(arg1:string):Promise<core.Response[string]>;

export function GetDeviceDictionaries():Promise<core.Response[[]main>;

export function GetLocalDictionaries():Promise<core.Response[[]main>;

export function GetWikiDetails(arg1:string):Promise<core.Response[github>;

export function ReadLocalDictionary(arg1:string):Promise<core.Response[github>;

export function SelectDevice():Promise<string>;
